### ISSUE TITLE
Create a header  

### ISSUE THREAD

**Issue by bsaavedrabo** [bereacollegemakerspace/bereacollegemakerspace.github.io#17]

**Comment by bsaavedrabo** [comment]
this is related to issue #16 and #4

**Comment by jazzij** [comment]
@bsaavedrabo If this is work on #4 or #16, then you do not need to create a new issue. Just make a comment and commit your changes referencing the correct issue

**Comment by bsaavedrabo** [comment]
https://www.youtube.com/watch?v=VRrEquQfh88&t=723s
