### ISSUE TITLE
Update TA Schedule on Homepage

### ISSUE THREAD

**Issue by jazzij** [bereacollegemakerspace/bereacollegemakerspace.github.io#2]
- Replace header text "Our Schedule" with "Fall 2022 Student Staff Schedule" 
- Update table with new times (below)

Monday | Tuesday | Wednesday | Thursday | Friday
-- | -- | -- | -- | --
4-6pm | N/A | 3.30-5.30pm | 7-9pm | 4-6pm

- Add third row to table: You can make appointment if needed! [Click to email us!](mailto:bereacollegemakerspace@gmail.com)

**Comment by jazzij** [comment]
Now that's it's Spring, need to update with Spring 2022 Staff Schedule. 
1. Easy update: just update change the table
2. More challenging: Embed the png of the schedule in nice way (download from here: https://www.instagram.com/p/Cnfe_eIJzBN) 
3. Ideal: Have both the image and Table in a nicely formatted way so it looks nice and also has accessible text adjacent or below.

**Comment by dixita9** [comment]
Updated the table with Spring 2023 schedule

**Comment by jazzij** [comment]
@dixita9 The image included for the schedule looks fine. However, the image source URL is currently an absolute URL.  You should use instead a relative URL. 
Why: With an absolute URL, this code will not run correctly on any computer except yours.
More on URL types:
https://www.tutorialspoint.com/difference-between-an-absolute-url-and-a-relative-url
https://stackoverflow.com/questions/2005079/absolute-vs-relative-urls
